### PR TITLE
Remove dependency on Layout Paragraphs

### LINKED ISSUE #29: Remove dependency on layout_paragraphs
Looks like we have a dependency on layout_paragraphs here.

https://github.com/localgovdrupal/localgov_page/blob/1.x/composer.json#L9

This should be in localgov_paragraphs OR better still in https://github.com/localgovdrupal/localgov_paragraphs/tree/2.x/modules/localgov_paragraphs_layout with a separate composer.json.

### LINKED ISSUE #36: Layout Paragraphs 2.x - test and upgrade
We want to upgrade to Layout Paragraphs 2.x

The dependencies have shifted so we alos have: 
 - https://github.com/localgovdrupal/localgov_subsites/pull/85
 - https://github.com/localgovdrupal/localgov_microsites/issues/84 
 - https://github.com/localgovdrupal/localgov_microsites/pull/97

### PR DESCRIPTION
**Pull request by stephen-cox**
Dependency on Layout Paragraphs with be added to LocalGov Paragraphs. This will allow use to upgrade to Layout Paragraphs 2.x without further releases.

 Fixes #36

See also:
- https://github.com/localgovdrupal/localgov_subsites/pull/85
- https://github.com/localgovdrupal/localgov_subsites/pull/109
- https://github.com/localgovdrupal/localgov_paragraphs/pull/83
- https://github.com/localgovdrupal/localgov_microsites/issues/84

### CODE REVIEW

**Comment by stephen-cox** [comment]
There are 3 pull requests that will upgrade Layout Paragraphs to version 2.

- https://github.com/localgovdrupal/localgov_paragraphs/pull/83
- https://github.com/localgovdrupal/localgov_page/pull/38
- https://github.com/localgovdrupal/localgov_subsites/pull/109

Anyone wanting to give this a whirl can use the `feature/layout-paragraphs-2` branch on [LocalGov Project](https://github.com/localgovdrupal/localgov_project/tree/feature/layout-paragraphs-2). There's a PR to test everything here: https://github.com/localgovdrupal/localgov_project/pull/91

It's been suggested that t[hese are released as major version updates](https://github.com/localgovdrupal/localgov_subsites/pull/85#issuecomment-1260737202); Paragraphs 3.0.0 and Subsites 3.0.0, Page is still dev. My suggestion is we do minor version updates and update the dependency in Page and Subsites to require the new minor version of Paragraphs; so Paragraphs 2.2.0 with Subsites 2.2.0 requiring `localgovdrupal/localgov_paragraphs:^2.2`.

**Comment by finnlewis** [comment]
We think this just needs the test improving, maybe specifying dependency? 
Also removing classy theme ([was it deprecated](https://www.drupal.org/project/drupal/issues/2352949)?) Use stark or stable. 

See: 
https://github.com/localgovdrupal/localgov_page/blob/feature/layout-paragraphs-2/tests/src/Functional/LocalGovPageTest.php#L37

**Comment by stephen-cox** [comment]
Tests are all passing

> We think this just needs the test improving, maybe specifying dependency?

Not sure what this means. What tests for this do you want?

> Also removing classy theme ([was it deprecated](https://www.drupal.org/project/drupal/issues/2352949)?) Use stark or stable.

I think this should be spun out into a separate issue.

**Review by finnlewis — APPROVED** [review]
Tests are now passing - yay! Thanks @stephen-cox !

**Comment by finnlewis** [comment]
> I think this should be spun out into a separate issue.

Done, see https://github.com/localgovdrupal/localgov_page/issues/39

**Pull request merged**
