### PR TITLE
Add new simple yet delightful 1, 2 and 3 column layouts. :)

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by msayoung** [comment]
Having thought about this some more, we may want to move this in to localgov_paragraphs module instead. Any thoughts @stephen-cox @finnlewis ?

**Review by finnlewis — APPROVED** [review]

**Review by stephen-cox — COMMENTED** [review]
Tests are failing because we need a release of localgov_paragraphs to pull in the new localgov_paragraphs_layout module.

**Comment by finnlewis** [comment]
@stephen-cox do you think we should switch to using a branch of localgov_paragraphs or do a release?

**Review by stephen-cox — APPROVED** [review]
Tests are passing now we have a release of LocalGov Paragraphs. All good to merge

**Pull request merged**
